In [1]:
import os
import pandas as pd
from collections import defaultdict

In [6]:
sp18_ext_path = "../resources/developed/sp18/"

resdir = "../out/internal_effect"

incsv_args = {
	"sep": "\t",
    "header": 0,
    "index_col": "gecodb",
    # all str, WC int, is linker pluralic bool
    "dtype": defaultdict(
        lambda: str,
        wc="int",
        is_linker_pl="bool"
    ),
	# = csv.QUOTE_NONE, separate by tabs only
    "quoting": 3
}

outcsv_args = {
    "sep": "\t",
    "index": True,
    "header": True
}

In [3]:
def read_sp18(name: str) -> pd.DataFrame:
	return pd.read_csv(
		os.path.join(sp18_ext_path, f"{name}.tsv"),
		**incsv_args
	)

In [7]:
sp18 = read_sp18("sp18")
sp18.sample(10)

,n1,n2,n1_pl_marker,n1_sem,n2_num,is_linker_pl,wc,context,context_id
gecodb,,,,,,,,,
loch_band,loch,band,_+=er_,ind,sg,False,157,Die Muffenseite sitzt in der Tonne . Auch dies...,4b65a9fe-dd42-469b-a50c-7ba791266461
element_unterteilung,element,unterteilung,_+e_,ind,pl,False,0,"""Um den nur durch FE beschriebenen Bereich """" ...",645dd8c9-be1a-4a9b-bd0b-a8fda1599029
rad_typ,rad,typ,_+=er_,ind,sg,False,365,"1976 begann Radprofi Wolfgang Renner neue , ei...",3924f2b4-a1cd-46f7-a907-4cc2f362ac89
schwester_gedicht,schwester,gedicht,_+n_,ind,sg,False,0,"Ach ja , den 24 Stunden-Karpfen-Cup hatten wir...",66989222-30c4-4e25-b988-e5676801f221
lied_überlieferung,lied,überlieferung,_+er_,ind,sg,False,1,"""Während letztere dem Gründungs­bestand der """"...",313e0b33-8f49-40c2-950c-c0d739680e1b
ohr_+en_zeugin,ohr,zeugin,_+en_,ind,sg,True,208,"Alles könnte eigentlich so weiterlaufen , bis ...",f3c21836-0bb8-48cf-807c-199703f9be1e
brett_+er_vorrat,brett,vorrat,_+er_,coll,sg,True,0,Oder ihre Interpretation des Auto-Ziegenproble...,48bd132b-2419-4eac-841c-7fb895bb2c0e
buch_projekt,buch,projekt,_+=er_,ind,sg,False,7272,"""Jörn hat viel Herzblut in dieses Projekt gest...",9951b784-1463-48d6-ae7c-a6849434a893
vater_+=_bild,vater,bild,_+=_,ind,pl,True,53,"""Andererseits ist das Ernährermodell in den Kö...",ef39546d-4b1a-454d-861f-350a1eba15f7
nation_+s_verständnis,nation,verständnis,_+en_,ind,sg,False,18,"""Damit vollzieht sich der Übergang von der """" ...",3fd0921f-6bf6-49fa-8ab6-ae9d5724f7c4

In [9]:
sp18 = sp18[~sp18.index.duplicated(keep="first")]
sp18

,n1,n2,n1_pl_marker,n1_sem,n2_num,is_linker_pl,wc,context,context_id
gecodb,,,,,,,,,
apfel_+=_achtel,apfel,achtel,_+=_,ind,pl,True,0,"Eiweiß dazugeben , Mandeln und Speißestärke un...",39d711a8-b8f0-40a4-ae07-515d675186f4
apfel_+=_allergie,apfel,allergie,_+=_,ind,sg,True,0,"In der Symptomsprache , nach der die Kreative ...",00d6a774-fbeb-450e-884b-39603425682b
apfel_+=_annahme,apfel,annahme,_+=_,ind,sg,True,0,Die Kapsel mit vielen Dokumenten wird vom Klem...,09ee64bd-555b-4784-89e3-de1e84dd0eb1
apfel_+=_anzahl,apfel,anzahl,_+=_,coll,sg,True,0,"Schaut gut aus , aber sind halt auch nur einfa...",c0c20966-15d5-4d49-aa09-da0d840148c1
apfel_+=_ausstellung,apfel,ausstellung,_+=_,konvc,sg,True,0,Wiederum für viele sehr interessant waren die ...,0a37e563-e6f4-4d3b-967a-5520008f5f6f
...,...,...,...,...,...,...,...,...,...
zitat_zusammenfassung,zitat,zusammenfassung,_+e_,ind,sg,False,0,"Zweitens kannst du dann wohl sicher sagen , da...",18d6a5f6-9d07-4b3c-a8b9-f766fc8301c3
zitat_zusammenstellung,zitat,zusammenstellung,_+e_,coll,pl,False,0,Ich lese diese Antworten nur selten . Aber wen...,891d1c31-9385-4a45-87c1-faac7e466668
zitat_zutraulichkeit,zitat,zutraulichkeit,_+e_,ind,sg,False,0,"""Wenn also insinuiert wird , daß die vulgär-dr...",96b3d000-bf76-4013-b0b9-e9e16e6f5eb6
zitat_zweck,zitat,zweck,_+e_,ind,pl,False,3,"Ein rechtmäßiger Zitatzweck liegt nur vor , we...",e5c5c0b1-a0d2-412d-b42b-e59439baeca4
zitat_überschrift,zitat,überschrift,_+e_,ind,sg,False,0,"""Hoffentlich passieren da nicht solche Dinge w...",b7d8c91e-85e6-40a0-a028-a84e9516418c

In [12]:
sp18 = sp18[sp18["wc"] >= 20]
sp18

,n1,n2,n1_pl_marker,n1_sem,n2_num,is_linker_pl,wc,context,context_id
gecodb,,,,,,,,,
apfel_+=_baum,apfel,baum,_+=_,ind,pl,True,122,An einem kleinem Flüsschen wandern wir bis sic...,578ee7e1-76f2-471b-b957-64a60b8cb33f
apfel_+=_säure,apfel,säure,_+=_,ind,pl,True,44,Säurearme Kaffeesorten werden meist weniger gu...,c6d4244b-4315-4cb5-a8c9-a937289c38d5
apfel_+=_wein,apfel,wein,_+=_,ind,sg,True,45,"""Wer diesen Titel erhält , darf zudem ein Jahr...",332458d8-cfeb-4983-8348-23fb4c318e43
apfel_bauer,apfel,bauer,_+=_,ind,sg,False,832,"""Bei schönstem Sonnenschein nimmt Hannes Pante...",9648573d-340f-484d-b991-55bfa2c86491
apfel_baum,apfel,baum,_+=_,ind,sg,False,27287,"""Zuweilen gibt es aber auch romantische Moment...",beddee9e-5790-4111-b893-7d00663e92ae
...,...,...,...,...,...,...,...,...,...
zitat_+e_sammlung,zitat,sammlung,_+e_,konvc,pl,True,92,"Nun ja , inzwischen haben auch Fachleute ganze...",23569f32-4e02-4c50-b4cb-7230df8639da
zitat_kunst,zitat,kunst,_+e_,ind,sg,False,21,"In Einschätzung des Gegenstands , von dem wir ...",df989c83-8cfb-4da6-bae1-154e7b7b9b27
zitat_montage,zitat,montage,_+e_,konvc,sg,False,59,"Das erste ist ein 1961 erschienener , populär ...",2ab481f5-d511-48f0-b3b8-3ea59421a58e
zitat_recht,zitat,recht,_+e_,ind,pl,False,168,"""So sehr Rechtssicherheit und Gleichheit vor d...",b532b79d-3559-410b-a3c4-e5d3bd4d16e8
zitat_spender,zitat,spender,_+e_,ind,sg,False,39,"Danke , das Kompliment erwidere ich gern . Mus...",49849022-b813-4851-bd7c-cc1486071e17

In [ ]:
sp18[(sp18["n1"] == "apfel") & (sp18["n2"] == "baum")]

,n1,n2,n1_pl_marker,n1_sem,n2_num,is_linker_pl,wc,context,context_id
gecodb,,,,,,,,,
apfel_+=_baum,apfel,baum,_+=_,ind,pl,True,122,An einem kleinem Flüsschen wandern wir bis sic...,578ee7e1-76f2-471b-b957-64a60b8cb33f
apfel_baum,apfel,baum,_+=_,ind,sg,False,27287,"""Zuweilen gibt es aber auch romantische Moment...",beddee9e-5790-4111-b893-7d00663e92ae

In [27]:
# coverage
def intpe_is_applicable(row: pd.Series, strict=True) -> bool:
    cond = ["coll"] if strict else ["coll", "konvc"]
    return row["n1_sem"] in cond

# regularity
def intpe_applies(row: pd.Series) -> bool:
    return row["is_linker_pl"]

def comp_constraints(row: pd.Series):
    to_return = []
    for s in [True, False]:
        is_applicable = intpe_is_applicable(row, strict=s)
        applies = intpe_applies(row) if is_applicable else False
        to_return.extend([is_applicable, applies])
    return to_return

In [ ]:
sp18["is_appl_strict"], sp18["applies_strict"], sp18["is_appl_lax"], sp18["applies_lax"] = zip(
    *sp18.apply(comp_constraints, axis=1)
)

In [29]:
sp18

,n1,n2,n1_pl_marker,n1_sem,n2_num,is_linker_pl,wc,context,context_id,is_appl_strict,applies_strict,is_appl_lax,applies_lax
gecodb,,,,,,,,,,,,,
apfel_+=_baum,apfel,baum,_+=_,ind,pl,True,122,An einem kleinem Flüsschen wandern wir bis sic...,578ee7e1-76f2-471b-b957-64a60b8cb33f,False,False,False,False
apfel_+=_säure,apfel,säure,_+=_,ind,pl,True,44,Säurearme Kaffeesorten werden meist weniger gu...,c6d4244b-4315-4cb5-a8c9-a937289c38d5,False,False,False,False
apfel_+=_wein,apfel,wein,_+=_,ind,sg,True,45,"""Wer diesen Titel erhält , darf zudem ein Jahr...",332458d8-cfeb-4983-8348-23fb4c318e43,False,False,False,False
apfel_bauer,apfel,bauer,_+=_,ind,sg,False,832,"""Bei schönstem Sonnenschein nimmt Hannes Pante...",9648573d-340f-484d-b991-55bfa2c86491,False,False,False,False
apfel_baum,apfel,baum,_+=_,ind,sg,False,27287,"""Zuweilen gibt es aber auch romantische Moment...",beddee9e-5790-4111-b893-7d00663e92ae,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
zitat_+e_sammlung,zitat,sammlung,_+e_,konvc,pl,True,92,"Nun ja , inzwischen haben auch Fachleute ganze...",23569f32-4e02-4c50-b4cb-7230df8639da,False,False,True,True
zitat_kunst,zitat,kunst,_+e_,ind,sg,False,21,"In Einschätzung des Gegenstands , von dem wir ...",df989c83-8cfb-4da6-bae1-154e7b7b9b27,False,False,False,False
zitat_montage,zitat,montage,_+e_,konvc,sg,False,59,"Das erste ist ein 1961 erschienener , populär ...",2ab481f5-d511-48f0-b3b8-3ea59421a58e,False,False,True,False
zitat_recht,zitat,recht,_+e_,ind,pl,False,168,"""So sehr Rechtssicherheit und Gleichheit vor d...",b532b79d-3559-410b-a3c4-e5d3bd4d16e8,False,False,False,False
zitat_spender,zitat,spender,_+e_,ind,sg,False,39,"Danke , das Kompliment erwidere ich gern . Mus...",49849022-b813-4851-bd7c-cc1486071e17,False,False,False,False

In [32]:
N = len(sp18)
intpe = pd.DataFrame({
    "strict": {
        "cvg": (xs := len(
            sp18[sp18["is_appl_strict"]]
        )) / N,
        "reg": len(
            sp18[sp18["applies_strict"]]
        ) / xs
    },
    "lax": {
        "cvg": (xl := len(
            sp18[sp18["is_appl_lax"]]
        )) / N,
        "reg": len(
            sp18[sp18["applies_lax"]]
        ) / xl
    }
})

intpe

       strict       lax
cvg  0.096606  0.133905
reg  0.756757  0.777159